// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("react-simple-maps");

function make(width, height, projection, $staropt$star, aspectRatio, $staropt$star$1, style, children) {
  var projectionConfig = $staropt$star ? $staropt$star[0] : /* record */[
      /* scale */205,
      /* xOffset : None */0,
      /* yOffset : None */0,
      /* rotation : :: */[
        -11,
        /* :: */[
          0,
          /* :: */[
            0,
            /* [] */0
          ]
        ]
      ],
      /* precision : None */0
    ];
  var viewBox = $staropt$star$1 ? $staropt$star$1[0] : "0 0 800 800";
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ComposableMap, {
              width: width,
              height: height,
              projection: projection,
              projectionConfig: projectionConfig,
              aspectRatio: aspectRatio,
              viewBox: viewBox,
              style: style
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
